---
common:
  disable_legacy_facts: true
appveyor.yml:
  delete: true
.github/workflows/test.yml:
  simplecov: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
.vscode/extensions.json:
  delete: true
.devcontainer/Dockerfile:
  delete: true
.devcontainer/devcontainer.json:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
Rakefile:
  linter_fail_on_warnings: true
spec/spec_helper.rb:
  coverage_report: false
  minimum_code_coverage_percentage: 100
